export const careerInfo = {
  "ai engineer": {
    salary: "₹10–25 LPA",
    demand: "Very High",
    difficulty: "Hard",
    learningTime: "6–12 Months",
  },

  "frontend developer": {
    salary: "₹6–15 LPA",
    demand: "High",
    difficulty: "Medium",
    learningTime: "4–8 Months",
  },

  "backend developer": {
    salary: "₹8–18 LPA",
    demand: "High",
    difficulty: "Medium",
    learningTime: "5–9 Months",
  },

  "full stack developer": {
    salary: "₹8–20 LPA",
    demand: "Very High",
    difficulty: "Medium",
    learningTime: "6–12 Months",
  },

  "data analyst": {
    salary: "₹5–12 LPA",
    demand: "High",
    difficulty: "Easy",
    learningTime: "3–6 Months",
  },

  "data scientist": {
    salary: "₹12–30 LPA",
    demand: "Very High",
    difficulty: "Hard",
    learningTime: "8–14 Months",
  },

  "cloud engineer": {
    salary: "₹10–22 LPA",
    demand: "High",
    difficulty: "Medium",
    learningTime: "6–10 Months",
  },

  "devops engineer": {
    salary: "₹12–25 LPA",
    demand: "Very High",
    difficulty: "Hard",
    learningTime: "8–12 Months",
  },

  "cybersecurity analyst": {
    salary: "₹8–20 LPA",
    demand: "Very High",
    difficulty: "Medium",
    learningTime: "6–12 Months",
  },
};
export const careerPaths = {
"ai engineer": [
{
title: "Learn Python",
why: "Primary language for AI development",
duration: "2 Weeks",
project: "Calculator App",
resources: ["CS50 Python", "Python.org"],
completed: false,
},
{
title: "Learn Git & GitHub",
why: "Version control for projects",
duration: "1 Week",
project: "Host Python Projects",
resources: ["GitHub Docs"],
completed: false,
},

{
title: "Learn SQL",
why: "Store and query data",
duration: "2 Weeks",
project: "Student Database",
resources: ["SQLBolt"],
completed: false,
},
{
title: "Learn Statistics",
why: "Foundation of machine learning",
duration: "2 Weeks",
project: "Analyze Dataset",
resources: ["Khan Academy"],
completed: false,
},
{
title: "Learn NumPy",
why: "Numerical computing in Python",
duration: "1 Week",
project: "Matrix Operations",
resources: ["NumPy Docs"],
completed: false,
},
{
title: "Learn Pandas",
why: "Data analysis and cleaning",
duration: "2 Weeks",
project: "CSV Data Cleaner",
resources: ["Pandas Docs"],
completed: false,
},
{
title: "Data Visualization",
why: "Understand and present data",
duration: "1 Week",
project: "Data Dashboard",
resources: ["Matplotlib"],
completed: false,
},
{
title: "Machine Learning Basics",
why: "Core AI concepts",
duration: "2 Weeks",
project: "Iris Classifier",
resources: ["Andrew Ng ML"],
completed: false,
},
{
title: "Supervised Learning",
why: "Most common ML approach",
duration: "2 Weeks",
project: "House Price Predictor",
resources: ["Scikit-Learn"],
completed: false,
},
{
title: "Unsupervised Learning",
why: "Discover hidden patterns",
duration: "1 Week",
project: "Customer Segmentation",
resources: ["Scikit-Learn"],
completed: false,
},
{
title: "Deep Learning",
why: "Power modern AI systems",
duration: "3 Weeks",
project: "Image Classifier",
resources: ["DeepLearning.AI"],
completed: false,
},
{
title: "Learn PyTorch",
why: "Industry-standard AI framework",
duration: "2 Weeks",
project: "Neural Network",
resources: ["PyTorch Docs"],
completed: false,
},
{
title: "Learn Transformers",
why: "Foundation of modern LLMs",
duration: "2 Weeks",
project: "Text Classifier",
resources: ["Hugging Face"],
completed: false,
},
{
title: "Learn LLMs",
why: "Build AI assistants",
duration: "2 Weeks",
project: "Chatbot",
resources: ["OpenAI Docs"],
completed: false,
},
{
title: "Build AI Portfolio Project",
why: "Demonstrate skills",
duration: "3 Weeks",
project: "AI Career Advisor",
resources: ["GitHub"],
completed: false,
},
{
title: "Deploy AI Application",
why: "Make projects accessible",
duration: "1 Week",
project: "Deploy on Vercel",
resources: ["Vercel Docs"],
completed: false,
},
{
title: "Prepare Resume & Portfolio",
why: "Showcase work professionally",
duration: "1 Week",
project: "Personal Portfolio",
resources: ["LinkedIn"],
completed: false,
},
{
title: "Interview Preparation",
why: "Land AI roles",
duration: "2 Weeks",
project: "Mock Interviews",
resources: ["LeetCode", "Interview Query"],
completed: false,
},
],

"data analyst": [
{
title: "Learn Excel",
why: "Analyze business data",
duration: "2 Weeks",
project: "Sales Dashboard",
resources: ["Microsoft Learn", "Excel Basics"],
completed: false,
},
{
title: "Learn SQL",
why: "Query databases",
duration: "3 Weeks",
project: "Database Analysis",
resources: ["SQLBolt", "W3Schools SQL"],
completed: false,
},
{
title: "Learn Power BI",
why: "Create dashboards",
duration: "3 Weeks",
project: "Business Dashboard",
resources: ["Power BI Docs"],
completed: false,
},
],

"frontend developer": [
{
title: "Learn HTML",
why: "Create webpage structure",
duration: "1 Week",
project: "Personal Profile Page",
resources: ["MDN HTML"],
completed: false,
},
{
title: "Learn CSS",
why: "Style webpages",
duration: "1 Week",
project: "Landing Page",
resources: ["MDN CSS"],
completed: false,
},
{
title: "Learn Flexbox",
why: "Build responsive layouts",
duration: "3 Days",
project: "Responsive Navigation Bar",
resources: ["CSS Tricks"],
completed: false,
},
{
title: "Learn CSS Grid",
why: "Create advanced layouts",
duration: "3 Days",
project: "Dashboard Layout",
resources: ["CSS Grid Garden"],
completed: false,
},
{
title: "Responsive Design",
why: "Support all devices",
duration: "1 Week",
project: "Mobile-Friendly Website",
resources: ["MDN Responsive Design"],
completed: false,
},
{
title: "JavaScript Basics",
why: "Add interactivity",
duration: "2 Weeks",
project: "Calculator App",
resources: ["JavaScript.info"],
completed: false,
},
{
title: "ES6+ Features",
why: "Write modern JavaScript",
duration: "1 Week",
project: "Refactor Old JS App",
resources: ["MDN ES6"],
completed: false,
},
{
title: "DOM Manipulation",
why: "Control webpage content",
duration: "1 Week",
project: "Interactive Todo App",
resources: ["JavaScript.info"],
completed: false,
},
{
  title: "Learn Git & GitHub",
  why: "Version control for projects",
  duration: "1 Week",
  project: "Host Python Projects",
  resources: [
    {
      name: "GitHub Docs",
      url: "https://docs.github.com/"
    }
  ],
  completed: false,
},
{
title: "React Fundamentals",
why: "Build modern interfaces",
duration: "2 Weeks",
project: "Weather App",
resources: ["React Docs"],
completed: false,
},
{
title: "React Hooks",
why: "Manage state and effects",
duration: "1 Week",
project: "Counter App",
resources: ["React Docs"],
completed: false,
},
{
title: "React Router",
why: "Build multi-page apps",
duration: "3 Days",
project: "Portfolio Website",
resources: ["React Router Docs"],
completed: false,
},
{
title: "API Integration",
why: "Fetch real-world data",
duration: "1 Week",
project: "Movie Search App",
resources: ["Fetch API Docs"],
completed: false,
},
{
title: "State Management",
why: "Handle complex applications",
duration: "1 Week",
project: "Shopping Cart",
resources: ["Redux Docs"],
completed: false,
},
{
title: "Tailwind CSS",
why: "Build modern UIs quickly",
duration: "1 Week",
project: "Startup Landing Page",
resources: ["Tailwind Docs"],
completed: false,
},
{
title: "Accessibility",
why: "Make websites usable for everyone",
duration: "3 Days",
project: "Accessible Form",
resources: ["WAI Guidelines"],
completed: false,
},
{
title: "Build Portfolio Project",
why: "Showcase frontend skills",
duration: "2 Weeks",
project: "Frontend Portfolio",
resources: ["GitHub"],
completed: false,
},
{
title: "Interview Preparation",
why: "Get frontend jobs",
duration: "2 Weeks",
project: "Mock Interviews",
resources: ["LeetCode"],
completed: false,
},
],

"backend developer": [
{
title: "Learn JavaScript",
why: "Backend programming basics",
duration: "2 Weeks",
project: "Calculator API",
resources: ["JavaScript.info"],
completed: false,
},
{
title: "Learn Node.js",
why: "Build server applications",
duration: "3 Weeks",
project: "REST API",
resources: ["Node.js Docs"],
completed: false,
},
{
title: "Learn MongoDB",
why: "Store application data",
duration: "2 Weeks",
project: "User Management System",
resources: ["MongoDB University"],
completed: false,
},
],

"full stack developer": [
{
title: "Learn HTML",
why: "Build webpage structure",
duration: "1 Week",
project: "Personal Profile Page",
resources: [
  {
    name: "MDN HTML",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML"
  }
],
completed: false,
},
{
title: "Learn CSS",
why: "Style websites",
duration: "1 Week",
project: "Landing Page",
resources: ["MDN CSS"],
completed: false,
},
{
title: "Learn JavaScript",
why: "Add website interactivity",
duration: "2 Weeks",
project: "Todo App",
resources: ["JavaScript.info"],
completed: false,
},
{
title: "Learn Git & GitHub",
why: "Version control projects",
duration: "1 Week",
project: "Upload Projects",
resources: ["GitHub Docs"],
completed: false,
},
{
title: "Learn React",
why: "Build modern frontend apps",
duration: "3 Weeks",
project: "Movie Search App",
resources: ["React Docs"],
completed: false,
},
{
title: "Learn Tailwind CSS",
why: "Design responsive UIs quickly",
duration: "1 Week",
project: "Portfolio UI",
resources: ["Tailwind Docs"],
completed: false,
},
{
title: "Learn Node.js",
why: "Run JavaScript on servers",
duration: "2 Weeks",
project: "Basic API",
resources: ["Node Docs"],
completed: false,
},
{
title: "Learn Express.js",
why: "Create backend applications",
duration: "1 Week",
project: "Blog API",
resources: ["Express Docs"],
completed: false,
},
{
title: "Learn MongoDB",
why: "Store application data",
duration: "2 Weeks",
project: "User Database",
resources: ["MongoDB University"],
completed: false,
},
{
title: "Build REST APIs",
why: "Connect frontend and backend",
duration: "1 Week",
project: "Task Manager API",
resources: ["Postman"],
completed: false,
},
{
title: "Authentication & JWT",
why: "Secure applications",
duration: "1 Week",
project: "Login System",
resources: ["JWT.io"],
completed: false,
},
{
title: "State Management",
why: "Manage application data",
duration: "1 Week",
project: "Shopping Cart",
resources: ["Redux Docs"],
completed: false,
},
{
title: "Frontend Deployment",
why: "Publish web apps",
duration: "1 Week",
project: "Deploy React App",
resources: ["Vercel Docs"],
completed: false,
},
{
title: "Backend Deployment",
why: "Host APIs online",
duration: "1 Week",
project: "Deploy Express API",
resources: ["Render Docs"],
completed: false,
},
{
title: "Build Full Stack Project",
why: "Combine all learned skills",
duration: "3 Weeks",
project: "E-Commerce Platform",
resources: ["GitHub"],
completed: false,
},
{
title: "Testing Basics",
why: "Improve application quality",
duration: "1 Week",
project: "Test API Endpoints",
resources: ["Jest Docs"],
completed: false,
},
{
title: "Create Portfolio Website",
why: "Showcase projects",
duration: "1 Week",
project: "Developer Portfolio",
resources: ["Netlify"],
completed: false,
},
{
title: "Interview Preparation",
why: "Get hired",
duration: "2 Weeks",
project: "Mock Interviews",
resources: ["LeetCode"],
completed: false,
},
],


"software engineer": [
{
title: "Learn Programming",
why: "Core engineering skill",
duration: "4 Weeks",
project: "Calculator App",
resources: ["CS50"],
completed: false,
},
{
title: "Learn Data Structures",
why: "Improve problem solving",
duration: "4 Weeks",
project: "Sorting Visualizer",
resources: ["GeeksforGeeks"],
completed: false,
},
{
title: "Build Projects",
why: "Gain experience",
duration: "6 Weeks",
project: "Management System",
resources: ["GitHub"],
completed: false,
},
],

"data scientist": [
{
title: "Learn Python",
why: "Data science foundation",
duration: "2 Weeks",
project: "Data Cleaner",
resources: ["Python.org"],
completed: false,
},
{
title: "Learn Statistics",
why: "Understand data patterns",
duration: "3 Weeks",
project: "Data Analysis Report",
resources: ["Khan Academy"],
completed: false,
},
{
title: "Learn Machine Learning",
why: "Predict outcomes",
duration: "4 Weeks",
project: "Customer Churn Model",
resources: ["Kaggle"],
completed: false,
},
],

"cloud engineer": [
{
title: "Learn Cloud Basics",
why: "Understand cloud computing",
duration: "2 Weeks",
project: "Cloud Notes",
resources: ["AWS Skill Builder"],
completed: false,
},
{
title: "Learn AWS",
why: "Deploy cloud solutions",
duration: "4 Weeks",
project: "Deploy Website",
resources: ["AWS Docs"],
completed: false,
},
{
title: "Learn Cloud Security",
why: "Protect cloud systems",
duration: "2 Weeks",
project: "Secure Architecture",
resources: ["AWS Security"],
completed: false,
},
],

"devops engineer": [
{
title: "Learn Linux",
why: "Most servers run Linux",
duration: "2 Weeks",
project: "Linux Server Setup",
resources: ["Linux Journey"],
completed: false,
},
{
title: "Learn Docker",
why: "Containerize applications",
duration: "3 Weeks",
project: "Dockerized App",
resources: ["Docker Docs"],
completed: false,
},
{
title: "Learn CI/CD",
why: "Automate deployments",
duration: "3 Weeks",
project: "GitHub Actions Pipeline",
resources: ["GitHub Docs"],
completed: false,
},
],

"cybersecurity analyst": [
{
title: "Learn Networking",
why: "Understand system communication",
duration: "3 Weeks",
project: "Network Diagram",
resources: ["Cisco Skills"],
completed: false,
},
{
title: "Learn Security Basics",
why: "Protect systems",
duration: "3 Weeks",
project: "Security Audit",
resources: ["TryHackMe"],
completed: false,
},
{
title: "Practice Ethical Hacking",
why: "Find vulnerabilities",
duration: "4 Weeks",
project: "CTF Challenges",
resources: ["Hack The Box"],
completed: false,
},
],

"mobile app developer": [
{
title: "Learn JavaScript",
why: "Foundation for React Native",
duration: "2 Weeks",
project: "Todo App",
resources: ["JavaScript.info"],
completed: false,
},
{
title: "Learn React Native",
why: "Build mobile apps",
duration: "4 Weeks",
project: "Weather App",
resources: ["React Native Docs"],
completed: false,
},
{
title: "Publish App",
why: "Deploy to users",
duration: "2 Weeks",
project: "Play Store App",
resources: ["Google Play Console"],
completed: false,
},
],

"ui ux designer": [
{
title: "Learn Design Principles",
why: "Create better interfaces",
duration: "2 Weeks",
project: "Redesign an App",
resources: ["Figma", "YouTube"],
completed: false,
},
{
title: "Learn Wireframing",
why: "Plan user flows",
duration: "2 Weeks",
project: "App Wireframe",
resources: ["Figma Docs"],
completed: false,
},
{
title: "Build Portfolio",
why: "Showcase design skills",
duration: "3 Weeks",
project: "Design Portfolio",
resources: ["Behance"],
completed: false,
},
],

"product manager": [
{
title: "Learn Product Thinking",
why: "Understand customer needs",
duration: "2 Weeks",
project: "Product Analysis",
resources: ["Product School"],
completed: false,
},
{
title: "Learn Roadmapping",
why: "Plan product growth",
duration: "2 Weeks",
project: "Product Roadmap",
resources: ["Atlassian"],
completed: false,
},
{
title: "Build Case Studies",
why: "Show PM skills",
duration: "3 Weeks",
project: "PM Portfolio",
resources: ["Medium"],
completed: false,
},
],
};

